version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db2
    environment:
      POSTGRES_USER: camilo
      POSTGRES_PASSWORD: camilo34
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
      